name: Notify Discord on Update

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"🔔 New update from upstream on \`${{ github.repository }}\` → ${GITHUB_SHA}\nhttps://github.com/${{ github.repository }}/commit/${GITHUB_SHA}\"}" \
               ${{ secrets.FEXEMU_WEBHOOK }}
