name: Notify Discord on New PR

on:
  push:
    branches:
      - 'pr/*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        run: |
          PR_NUM=$(echo "${GITHUB_REF}" | sed 's#refs/heads/pr/##')
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"https://github.com/FEX-Emu/FEX/pull/${PR_NUM}\"}" \
               ${{ secrets.FEXEMU_WEBHOOK }}
